name: Go Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.4'

#      - name: Run tests 2A
#        run: |
#          cd src/raft
#          for i in {1..100}; do
#            echo "Running test 2A round: $i"
#            go test -run 2A
#          done

      - name: Run tests 2B
        run: |
          cd src/raft
          for i in {1..5}; do
            echo "Running test 2B round: $i"
            go test -run 2B
          done

      - name: Run tests 2C
        run: |
          cd src/raft
          for i in {1..30}; do
            echo "Running test 2C round: $i"
            go test -run 2C
          done